#!/usr/bin/env bash
# init.sh — one-time (idempotent) setup of a target repo for the maestro pipeline.
#
# Creates the triage + pipeline labels, installs the scripts and generated config
# under .maestro/ (machine-local), ensures .gitignore + a PR template, and seeds the
# project context files (CLAUDE.md, AGENTS.md, rules, glossary). Safe to re-run.
set -euo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

maestro_require_cmd gh jq git

repo="$(maestro_repo)"
echo "▶ maestro init for ${repo}"
echo

# 1. Labels -----------------------------------------------------------------
echo "① Labels"
bash "${MAESTRO_LIB_DIR}/ensure-labels.sh" | sed 's/^/   /'
echo

# 2. .maestro/ runtime: install scripts + generated config ---------------------
echo "② Runtime (.maestro/)"
mkdir -p "${MAESTRO_DIR}/scripts"
cp "${MAESTRO_LIB_DIR}"/*.sh "${MAESTRO_DIR}/scripts/"
chmod +x "${MAESTRO_DIR}/scripts/"*.sh
abs_scripts="$(cd "${MAESTRO_DIR}/scripts" && pwd)"
echo "   installed scripts -> ${MAESTRO_DIR}/scripts/"

if [[ -f "${MAESTRO_DIR}/config.sh" ]]; then
  # Preserve user config; just refresh the MAESTRO_SCRIPTS path.
  if grep -q '^MAESTRO_SCRIPTS=' "${MAESTRO_DIR}/config.sh"; then
    tmp="${MAESTRO_DIR}/config.sh.tmp.$$"
    sed "s#^MAESTRO_SCRIPTS=.*#MAESTRO_SCRIPTS=\"${abs_scripts}\"#" "${MAESTRO_DIR}/config.sh" > "$tmp" && mv "$tmp" "${MAESTRO_DIR}/config.sh"
  else
    printf 'MAESTRO_SCRIPTS="%s"\n' "$abs_scripts" >> "${MAESTRO_DIR}/config.sh"
  fi
  echo "   refreshed ${MAESTRO_DIR}/config.sh (kept your overrides)"
else
  cat > "${MAESTRO_DIR}/config.sh" <<EOF
# maestro config — machine-local, gitignored. Generated by /maestro:init.
MAESTRO_SCRIPTS="${abs_scripts}"

# Max issue-implementer subagents to fan out in parallel.
# MAESTRO_MAX_PARALLEL=3

# Quality-gate overrides. If unset, the gate auto-detects the toolchain
# (package.json / go.mod / Cargo.toml / pyproject.toml / Makefile).
# Set any to the empty string to skip that step.
# MAESTRO_INSTALL_CMD=""
# MAESTRO_LINT_CMD=""
# MAESTRO_TYPECHECK_CMD=""
# MAESTRO_TEST_CMD=""
EOF
  echo "   wrote ${MAESTRO_DIR}/config.sh"
fi
echo

# 3. .gitignore -------------------------------------------------------------
echo "③ .gitignore"
touch .gitignore
for pat in '.maestro/' '*.local.md'; do
  grep -qxF "$pat" .gitignore || { printf '%s\n' "$pat" >> .gitignore; echo "   + $pat"; }
done
echo

# 4. Issue & PR templates ---------------------------------------------------
echo "④ Issue & PR templates"
tpl="${MAESTRO_LIB_DIR}/../templates"
mkdir -p .github/ISSUE_TEMPLATE
if [[ -f .github/pull_request_template.md ]]; then
  echo "   .github/pull_request_template.md already exists — left as-is"
elif [[ -f "${tpl}/pull_request.md" ]]; then
  cp "${tpl}/pull_request.md" .github/pull_request_template.md
  echo "   wrote .github/pull_request_template.md"
fi
if [[ ! -f .github/ISSUE_TEMPLATE/prd.md && -f "${tpl}/prd.md" ]]; then
  { printf -- '---\nname: PRD\nabout: Product requirements (parent epic); usually created by /maestro:plan-with-agent\nlabels: agent:prd\n---\n\n'; cat "${tpl}/prd.md"; } > .github/ISSUE_TEMPLATE/prd.md
  echo "   wrote .github/ISSUE_TEMPLATE/prd.md"
fi
if [[ ! -f .github/ISSUE_TEMPLATE/task.md && -f "${tpl}/task.md" ]]; then
  { printf -- '---\nname: Task (vertical slice)\nabout: One implementable vertical slice; usually created by /maestro:issues\nlabels: agent:ready-for-agent\n---\n\n'; cat "${tpl}/task.md"; } > .github/ISSUE_TEMPLATE/task.md
  echo "   wrote .github/ISSUE_TEMPLATE/task.md"
fi
echo

# 5. Project context, rules & glossary -------------------------------------
echo "⑤ Project context, rules & glossary"
tpl="${MAESTRO_LIB_DIR}/../templates"
mkdir -p .claude/rules docs
_seed() { # _seed <template> <dest>
  if [[ -f "$2" ]]; then echo "   ${2} already exists — left as-is"
  elif [[ -f "$1" ]]; then cp "$1" "$2"; echo "   wrote ${2}"
  else maestro_die "template missing: $1 — this maestro install looks incomplete; reinstall the plugin and re-run /maestro:init"; fi
}
_seed "${tpl}/maestro.rules.md" ".claude/rules/maestro.md"
_seed "${tpl}/learnings.md"  ".claude/rules/learnings.md"
_seed "${tpl}/GLOSSARY.md"   "docs/GLOSSARY.md"
_seed "${tpl}/CLAUDE.md"     "CLAUDE.md"
_seed "${tpl}/AGENTS.md"     "AGENTS.md"
if [[ ! -f CONTEXT.md ]]; then
  printf '# Glossary\n\n<!-- Domain terms, one per heading. Populated by /maestro:plan-with-agent. -->\n' > CONTEXT.md
  echo "   wrote CONTEXT.md"
else
  echo "   CONTEXT.md already exists — left as-is"
fi
echo

maestro_log init repo="$repo"

echo "✅ maestro init complete for ${repo}."
echo
echo "Next:"
echo "  • Restart Claude Code (or /reload-plugins) so the issue-implementer agent + /maestro:* commands load."
echo "  • Then: /maestro:plan-with-agent → /maestro:issues → /maestro:ship <issue> (or /maestro:drain)."
echo "  • Autonomous: /maestro:auto. Review a PR: /maestro:review. Teach a correction: /maestro:learn."
