#!/usr/bin/env bash
# init.sh — one-time (idempotent) setup of a target repo for the ai-sdlc pipeline.
#
# Creates the triage + pipeline labels, installs the scripts and generated config
# under .sdlc/ (machine-local), ensures .gitignore + a PR template, and checks
# that the aihero front-end skills are available. Safe to re-run.
set -euo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

sdlc_require_cmd gh jq git

repo="$(sdlc_repo)"
echo "▶ ai-sdlc init for ${repo}"
echo

# 1. Labels -----------------------------------------------------------------
echo "① Labels"
bash "${SDLC_LIB_DIR}/ensure-labels.sh" | sed 's/^/   /'
echo

# 2. .sdlc/ runtime: install scripts + generated config ---------------------
echo "② Runtime (.sdlc/)"
mkdir -p "${SDLC_DIR}/scripts"
cp "${SDLC_LIB_DIR}"/*.sh "${SDLC_DIR}/scripts/"
chmod +x "${SDLC_DIR}/scripts/"*.sh
abs_scripts="$(cd "${SDLC_DIR}/scripts" && pwd)"
echo "   installed scripts -> ${SDLC_DIR}/scripts/"

if [[ -f "${SDLC_DIR}/config.sh" ]]; then
  # Preserve user config; just refresh the SDLC_SCRIPTS path.
  if grep -q '^SDLC_SCRIPTS=' "${SDLC_DIR}/config.sh"; then
    tmp="${SDLC_DIR}/config.sh.tmp.$$"
    sed "s#^SDLC_SCRIPTS=.*#SDLC_SCRIPTS=\"${abs_scripts}\"#" "${SDLC_DIR}/config.sh" > "$tmp" && mv "$tmp" "${SDLC_DIR}/config.sh"
  else
    printf 'SDLC_SCRIPTS="%s"\n' "$abs_scripts" >> "${SDLC_DIR}/config.sh"
  fi
  echo "   refreshed ${SDLC_DIR}/config.sh (kept your overrides)"
else
  cat > "${SDLC_DIR}/config.sh" <<EOF
# ai-sdlc config — machine-local, gitignored. Generated by /sdlc:init.
SDLC_SCRIPTS="${abs_scripts}"

# Max issue-implementer subagents to fan out in parallel.
# SDLC_MAX_PARALLEL=3

# Quality-gate overrides. If unset, the gate auto-detects the toolchain
# (package.json / go.mod / Cargo.toml / pyproject.toml / Makefile).
# Set any to the empty string to skip that step.
# SDLC_INSTALL_CMD=""
# SDLC_LINT_CMD=""
# SDLC_TYPECHECK_CMD=""
# SDLC_TEST_CMD=""
EOF
  echo "   wrote ${SDLC_DIR}/config.sh"
fi
echo

# 3. .gitignore -------------------------------------------------------------
echo "③ .gitignore"
touch .gitignore
for pat in '.sdlc/' '*.local.md'; do
  grep -qxF "$pat" .gitignore || { printf '%s\n' "$pat" >> .gitignore; echo "   + $pat"; }
done
echo

# 4. PR template ------------------------------------------------------------
echo "④ PR template"
mkdir -p .github
if [[ -f .github/pull_request_template.md ]]; then
  echo "   .github/pull_request_template.md already exists — left as-is"
else
  cat > .github/pull_request_template.md <<'EOF'
> *This was generated by an AI agent in the ai-sdlc pipeline.*

Closes #

## Summary

<!-- What changed, and how it satisfies the issue's acceptance criteria. -->

## Acceptance criteria

<!-- Mirror the issue's checklist; tick what this PR satisfies. -->
EOF
  echo "   wrote .github/pull_request_template.md"
fi
echo

# 5. Project context, rules & glossary -------------------------------------
echo "⑤ Project context, rules & glossary"
tpl="${SDLC_LIB_DIR}/../templates"
mkdir -p .claude/rules docs
_seed() { # _seed <template> <dest>
  if [[ -f "$2" ]]; then echo "   ${2} already exists — left as-is"
  elif [[ -f "$1" ]]; then cp "$1" "$2"; echo "   wrote ${2}"
  else sdlc_warn "template missing: $(basename "$1")"; fi
}
_seed "${tpl}/sdlc.rules.md" ".claude/rules/sdlc.md"
_seed "${tpl}/GLOSSARY.md"   "docs/GLOSSARY.md"
_seed "${tpl}/CLAUDE.md"     "CLAUDE.md"
_seed "${tpl}/AGENTS.md"     "AGENTS.md"
if [[ ! -f CONTEXT.md ]]; then
  printf '# Glossary\n\n<!-- Domain terms, one per heading. Populated by /sdlc:plan-with-agent. -->\n' > CONTEXT.md
  echo "   wrote CONTEXT.md"
else
  echo "   CONTEXT.md already exists — left as-is"
fi
echo

# 6. aihero front-end skills check -----------------------------------------
echo "⑥ aihero front-end skills (composed by the pipeline)"
missing=()
for s in to-prd to-issues grill-with-docs triage tdd; do
  if [[ -d "${HOME}/.claude/skills/${s}" ]]; then
    echo "   ✔ ${s}"
  else
    echo "   ✘ ${s} (not found in ~/.claude/skills)"
    missing+=("$s")
  fi
done
echo

sdlc_log init repo="$repo" missing_skills="${missing[*]:-none}"

echo "✅ ai-sdlc init complete for ${repo}."
echo
echo "Next:"
echo "  • Restart Claude Code (or /reload-plugins) so the issue-implementer agent + /sdlc:* commands load."
if [[ ${#missing[@]} -gt 0 ]]; then
  echo "  • Install the missing aihero skills (${missing[*]}) from https://www.aihero.dev/skills,"
  echo "    or run /setup-matt-pocock-skills, so /sdlc:prd, /sdlc:align and /sdlc:issues work."
fi
echo "  • Then: /sdlc:prd → /sdlc:align → /sdlc:issues → /sdlc:ship (or /sdlc:drain)."
