#!/usr/bin/env bash
# init.sh — one-time (idempotent) setup of a target repo for the ai-sdlc pipeline.
#
# Creates the triage + pipeline labels, installs the scripts and generated config
# under .sdlc/ (machine-local), ensures .gitignore + a PR template, and seeds the
# project context files (CLAUDE.md, AGENTS.md, rules, glossary). Safe to re-run.
set -euo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

sdlc_require_cmd gh jq git

repo="$(sdlc_repo)"
echo "▶ ai-sdlc init for ${repo}"
echo

# 1. Labels -----------------------------------------------------------------
echo "① Labels"
bash "${SDLC_LIB_DIR}/ensure-labels.sh" | sed 's/^/   /'
echo

# 2. .sdlc/ runtime: install scripts + generated config ---------------------
echo "② Runtime (.sdlc/)"
mkdir -p "${SDLC_DIR}/scripts"
cp "${SDLC_LIB_DIR}"/*.sh "${SDLC_DIR}/scripts/"
chmod +x "${SDLC_DIR}/scripts/"*.sh
abs_scripts="$(cd "${SDLC_DIR}/scripts" && pwd)"
echo "   installed scripts -> ${SDLC_DIR}/scripts/"

if [[ -f "${SDLC_DIR}/config.sh" ]]; then
  # Preserve user config; just refresh the SDLC_SCRIPTS path.
  if grep -q '^SDLC_SCRIPTS=' "${SDLC_DIR}/config.sh"; then
    tmp="${SDLC_DIR}/config.sh.tmp.$$"
    sed "s#^SDLC_SCRIPTS=.*#SDLC_SCRIPTS=\"${abs_scripts}\"#" "${SDLC_DIR}/config.sh" > "$tmp" && mv "$tmp" "${SDLC_DIR}/config.sh"
  else
    printf 'SDLC_SCRIPTS="%s"\n' "$abs_scripts" >> "${SDLC_DIR}/config.sh"
  fi
  echo "   refreshed ${SDLC_DIR}/config.sh (kept your overrides)"
else
  cat > "${SDLC_DIR}/config.sh" <<EOF
# ai-sdlc config — machine-local, gitignored. Generated by /sdlc:init.
SDLC_SCRIPTS="${abs_scripts}"

# Max issue-implementer subagents to fan out in parallel.
# SDLC_MAX_PARALLEL=3

# Quality-gate overrides. If unset, the gate auto-detects the toolchain
# (package.json / go.mod / Cargo.toml / pyproject.toml / Makefile).
# Set any to the empty string to skip that step.
# SDLC_INSTALL_CMD=""
# SDLC_LINT_CMD=""
# SDLC_TYPECHECK_CMD=""
# SDLC_TEST_CMD=""
EOF
  echo "   wrote ${SDLC_DIR}/config.sh"
fi
echo

# 3. .gitignore -------------------------------------------------------------
echo "③ .gitignore"
touch .gitignore
for pat in '.sdlc/' '*.local.md'; do
  grep -qxF "$pat" .gitignore || { printf '%s\n' "$pat" >> .gitignore; echo "   + $pat"; }
done
echo

# 4. Issue & PR templates ---------------------------------------------------
echo "④ Issue & PR templates"
tpl="${SDLC_LIB_DIR}/../templates"
mkdir -p .github/ISSUE_TEMPLATE
if [[ -f .github/pull_request_template.md ]]; then
  echo "   .github/pull_request_template.md already exists — left as-is"
elif [[ -f "${tpl}/pull_request.md" ]]; then
  cp "${tpl}/pull_request.md" .github/pull_request_template.md
  echo "   wrote .github/pull_request_template.md"
fi
if [[ ! -f .github/ISSUE_TEMPLATE/prd.md && -f "${tpl}/prd.md" ]]; then
  { printf -- '---\nname: PRD\nabout: Product requirements (parent epic); usually created by /sdlc:plan-with-agent\nlabels: prd\n---\n\n'; cat "${tpl}/prd.md"; } > .github/ISSUE_TEMPLATE/prd.md
  echo "   wrote .github/ISSUE_TEMPLATE/prd.md"
fi
if [[ ! -f .github/ISSUE_TEMPLATE/task.md && -f "${tpl}/task.md" ]]; then
  { printf -- '---\nname: Task (vertical slice)\nabout: One implementable vertical slice; usually created by /sdlc:issues\nlabels: ready-for-agent\n---\n\n'; cat "${tpl}/task.md"; } > .github/ISSUE_TEMPLATE/task.md
  echo "   wrote .github/ISSUE_TEMPLATE/task.md"
fi
echo

# 5. Project context, rules & glossary -------------------------------------
echo "⑤ Project context, rules & glossary"
tpl="${SDLC_LIB_DIR}/../templates"
mkdir -p .claude/rules docs
_seed() { # _seed <template> <dest>
  if [[ -f "$2" ]]; then echo "   ${2} already exists — left as-is"
  elif [[ -f "$1" ]]; then cp "$1" "$2"; echo "   wrote ${2}"
  else sdlc_warn "template missing: $(basename "$1")"; fi
}
_seed "${tpl}/sdlc.rules.md" ".claude/rules/sdlc.md"
_seed "${tpl}/learnings.md"  ".claude/rules/learnings.md"
_seed "${tpl}/GLOSSARY.md"   "docs/GLOSSARY.md"
_seed "${tpl}/CLAUDE.md"     "CLAUDE.md"
_seed "${tpl}/AGENTS.md"     "AGENTS.md"
if [[ ! -f CONTEXT.md ]]; then
  printf '# Glossary\n\n<!-- Domain terms, one per heading. Populated by /sdlc:plan-with-agent. -->\n' > CONTEXT.md
  echo "   wrote CONTEXT.md"
else
  echo "   CONTEXT.md already exists — left as-is"
fi
echo

sdlc_log init repo="$repo"

echo "✅ ai-sdlc init complete for ${repo}."
echo
echo "Next:"
echo "  • Restart Claude Code (or /reload-plugins) so the issue-implementer agent + /sdlc:* commands load."
echo "  • Then: /sdlc:plan-with-agent → /sdlc:issues → /sdlc:ship <issue> (or /sdlc:drain)."
echo "  • Autonomous: /sdlc:auto. Review a PR: /sdlc:review. Teach a correction: /sdlc:learn."
