#!/usr/bin/env bash
# lib.sh — shared helpers for the ai-sdlc scripts.
#
# Source this from every other script:
#   source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"
#
# It is intentionally side-effect-free on source (defines vars + functions only),
# so it is safe to source from hooks, skills, and other scripts. Scripts that are
# entry points should set `set -euo pipefail` themselves.
#
# Everything here assumes the current working directory is inside the *target*
# repository (the repo whose issues/PRs we are driving) — `gh` and `git` pick the
# repo up from the cwd, so a per-issue worktree transparently targets the same repo.

# ---------------------------------------------------------------------------
# Configuration (override via environment or .sdlc/config.sh in the target repo)
# ---------------------------------------------------------------------------

# Where per-repo state lives (logs, loop state, config).
: "${SDLC_DIR:=.sdlc}"

# Load per-repo overrides if present. config.sh may set any SDLC_* variable or
# any of the label names below. Written by `/sdlc:init`.
if [[ -f "${SDLC_DIR}/config.sh" ]]; then
  # shellcheck disable=SC1090
  source "${SDLC_DIR}/config.sh"
fi

# Triage label vocabulary (canonical aihero roles). Override in config.sh if the
# repo already uses different strings.
: "${SDLC_LABEL_READY_AGENT:=ready-for-agent}"   # fully specified, AFK-ready
: "${SDLC_LABEL_READY_HUMAN:=ready-for-human}"    # needs a human
: "${SDLC_LABEL_NEEDS_TRIAGE:=needs-triage}"
: "${SDLC_LABEL_NEEDS_INFO:=needs-info}"
: "${SDLC_LABEL_WONTFIX:=wontfix}"
: "${SDLC_LABEL_BUG:=bug}"
: "${SDLC_LABEL_ENHANCEMENT:=enhancement}"

# Pipeline labels added by this plugin.
: "${SDLC_LABEL_AFK:=afk}"                 # can be implemented with no human
: "${SDLC_LABEL_HITL:=hitl}"               # needs human interaction
: "${SDLC_LABEL_PRD:=prd}"                 # a PRD / epic parent issue
: "${SDLC_LABEL_IN_PROGRESS:=in-progress}" # an agent is actively working it
: "${SDLC_LABEL_IN_REVIEW:=in-review}"     # a PR is open, awaiting human review

# Behaviour.
: "${SDLC_MAX_PARALLEL:=3}"                          # default fan-out concurrency
: "${SDLC_WORKTREE_DIR:=../ai-sdlc-worktrees}"       # where per-issue worktrees go
: "${SDLC_BRANCH_PREFIX:=sdlc/issue-}"               # branch name prefix

# ---------------------------------------------------------------------------
# Output helpers
# ---------------------------------------------------------------------------

sdlc_warn() { printf 'sdlc: %s\n' "$*" >&2; }
sdlc_die()  { printf 'sdlc: error: %s\n' "$*" >&2; exit 1; }

# require_cmd cmd... — fail if any command is missing.
sdlc_require_cmd() {
  local missing=0 c
  for c in "$@"; do
    command -v "$c" >/dev/null 2>&1 || { sdlc_warn "required command not found: $c"; missing=1; }
  done
  [[ $missing -eq 0 ]] || sdlc_die "install the missing command(s) above and retry"
}

# ---------------------------------------------------------------------------
# Repo / git helpers
# ---------------------------------------------------------------------------

# sdlc_repo — print the GitHub repo as owner/name. Cached per process.
sdlc_repo() {
  if [[ -z "${_SDLC_REPO:-}" ]]; then
    _SDLC_REPO="$(gh repo view --json nameWithOwner --jq .nameWithOwner 2>/dev/null || true)"
    [[ -n "$_SDLC_REPO" ]] || sdlc_die "could not determine the GitHub repo (run inside a repo with a GitHub remote, gh authenticated)"
  fi
  printf '%s\n' "$_SDLC_REPO"
}

# sdlc_default_branch — print the repo's default branch (e.g. main).
sdlc_default_branch() {
  if [[ -z "${_SDLC_DEFAULT_BRANCH:-}" ]]; then
    _SDLC_DEFAULT_BRANCH="$(gh repo view --json defaultBranchRef --jq .defaultBranchRef.name 2>/dev/null || true)"
    [[ -n "$_SDLC_DEFAULT_BRANCH" ]] || _SDLC_DEFAULT_BRANCH="main"
  fi
  printf '%s\n' "$_SDLC_DEFAULT_BRANCH"
}

# sdlc_slug "Some Title" — kebab-case, ascii, max ~50 chars, for branch names.
sdlc_slug() {
  printf '%s' "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//' \
    | cut -c1-50 \
    | sed -E 's/-+$//'
}

# sdlc_branch_for <issue> <slug> — deterministic branch name for an issue.
sdlc_branch_for() { printf '%s%s-%s\n' "$SDLC_BRANCH_PREFIX" "$1" "$2"; }

# ---------------------------------------------------------------------------
# Conventions
# ---------------------------------------------------------------------------

# The disclaimer that must lead every issue/PR comment the pipeline posts
# (mirrors the aihero `triage` convention).
sdlc_disclaimer() { printf '> *This was generated by an AI agent in the ai-sdlc pipeline.*\n'; }

# sdlc_log <event> [key=value ...] — append a JSON line to .sdlc/log.jsonl.
# Timestamps via `date` are fine here (these scripts are not workflow-replayed).
sdlc_log() {
  local event="$1"; shift || true
  mkdir -p "$SDLC_DIR"
  local kv_json="{}" k v
  for kv in "$@"; do
    k="${kv%%=*}"; v="${kv#*=}"
    kv_json="$(jq -c --arg k "$k" --arg v "$v" '. + {($k): $v}' <<<"$kv_json")"
  done
  jq -cn --arg ts "$(date -u +%Y-%m-%dT%H:%M:%SZ)" --arg event "$event" --argjson data "$kv_json" \
    '{ts: $ts, event: $event} + $data' >>"${SDLC_DIR}/log.jsonl"
}
