#!/usr/bin/env bash
# ai-disclaimer-guard.sh — PreToolUse (Bash) advisory.
#
# Nudges (does NOT block) when an issue/PR comment is being posted without the
# AI disclaimer the pipeline conventionally leads with. The pipeline's open-pr.sh
# already adds it; this only reminds for manual `gh issue/pr comment` calls.
set -uo pipefail

INPUT="$(cat)"
cmd="$(printf '%s' "$INPUT" | jq -r '.tool_input.command // ""' 2>/dev/null || echo "")"

# Only consider issue/PR comment posts.
printf '%s' "$cmd" | grep -qE 'gh[[:space:]]+(issue|pr)[[:space:]]+comment' || exit 0
# Already has a disclaimer marker? Nothing to do.
printf '%s' "$cmd" | grep -qiE 'generated by (an )?ai' && exit 0

echo "ai-sdlc reminder: pipeline comments should start with the disclaimer — '> *This was generated by an AI agent in the ai-sdlc pipeline.*'. (open-pr.sh adds it automatically; include it for manual comments.)" >&2
exit 0   # advisory only — never blocks
