#!/usr/bin/env bash
# Unit tests for the pure helpers in plugins/maestro/scripts/lib.sh.
set -u
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
# shellcheck source=tests/lib/assert.sh
source "$HERE/../lib/assert.sh"
# shellcheck source=plugins/maestro/scripts/lib.sh
source "$ROOT/plugins/maestro/scripts/lib.sh"

# maestro_slug — kebab-case, ascii, trimmed.
assert_eq "some-title" "$(maestro_slug 'Some Title')" "slug lowercases + hyphenates"
assert_eq "add-maestro-merge-pr" "$(maestro_slug 'Add /maestro:merge_pr!!')" "slug strips punctuation"
assert_eq "a-b" "$(maestro_slug '  --A   B--  ')" "slug trims leading/trailing separators"

# maestro_branch_for — deterministic branch name.
assert_eq "maestro/issue-12-some-title" "$(maestro_branch_for 12 some-title)" "branch name format"

# maestro_disclaimer — leads every pipeline comment.
assert_contains "$(maestro_disclaimer)" "generated by an AI agent" "disclaimer text"

# maestro_version — read from the shipped manifest (this repo: 0.1.0).
assert_eq "0.1.0" "$(maestro_version)" "version from plugin.json"

# maestro_perm_ok — write+ permissions pass; weaker ones fail.
assert_status 0 maestro_perm_ok ADMIN
assert_status 0 maestro_perm_ok WRITE
assert_status 0 maestro_perm_ok MAINTAIN
assert_status 1 maestro_perm_ok READ
assert_status 1 maestro_perm_ok TRIAGE
assert_status 1 maestro_perm_ok ""

# maestro_new_run_id — sortable UTC stamp + pid.
assert_matches "$(maestro_new_run_id)" '^[0-9]{8}-[0-9]{6}-[0-9]+$' "run id format"

# maestro_log — stamps run_id from MAESTRO_RUN_ID, and from .maestro/run.local.
tmp="$(mktemp -d)"
( cd "$tmp"; export MAESTRO_RUN_ID="ENVRUN"; maestro_log demo issue=7 )
line="$(cat "$tmp/.maestro/log.jsonl" 2>/dev/null || true)"
assert_contains "$line" '"event":"demo"' "log writes the event"
assert_contains "$line" '"issue":"7"' "log writes kv pairs"
assert_contains "$line" '"run_id":"ENVRUN"' "log stamps run_id from env"

tmp2="$(mktemp -d)"; mkdir -p "$tmp2/.maestro"; printf 'FILERUN\n' > "$tmp2/.maestro/run.local"
( cd "$tmp2"; unset MAESTRO_RUN_ID; maestro_log demo2 )
line2="$(cat "$tmp2/.maestro/log.jsonl" 2>/dev/null || true)"
assert_contains "$line2" '"run_id":"FILERUN"' "log falls back to run.local"

rm -rf "$tmp" "$tmp2"
t_end
